/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoTrabalhamosRouteImport } from './routes/como-trabalhamos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ForjaAiRouteImport } from './routes/forja-ai'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as RadarAiRouteImport } from './routes/radar-ai'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as TrilhaAiRouteImport } from './routes/trilha-ai'
import { Route as ViradaInteligenteRouteImport } from './routes/virada-inteligente'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesSlugRouteImport } from './routes/cases/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabalhamosRoute = ComoTrabalhamosRouteImport.update({
  id: '/como-trabalhamos',
  path: '/como-trabalhamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ForjaAiRoute = ForjaAiRouteImport.update({
  id: '/forja-ai',
  path: '/forja-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarAiRoute = RadarAiRouteImport.update({
  id: '/radar-ai',
  path: '/radar-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaAiRoute = TrilhaAiRouteImport.update({
  id: '/trilha-ai',
  path: '/trilha-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ViradaInteligenteRoute = ViradaInteligenteRouteImport.update({
  id: '/virada-inteligente',
  path: '/virada-inteligente',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/forja-ai': typeof ForjaAiRoute
  '/portfolio': typeof PortfolioRoute
  '/quem-somos': typeof QuemSomosRoute
  '/radar-ai': typeof RadarAiRoute
  '/solucoes': typeof SolucoesRoute
  '/trilha-ai': typeof TrilhaAiRoute
  '/virada-inteligente': typeof ViradaInteligenteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/forja-ai': typeof ForjaAiRoute
  '/portfolio': typeof PortfolioRoute
  '/quem-somos': typeof QuemSomosRoute
  '/radar-ai': typeof RadarAiRoute
  '/solucoes': typeof SolucoesRoute
  '/trilha-ai': typeof TrilhaAiRoute
  '/virada-inteligente': typeof ViradaInteligenteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/forja-ai': typeof ForjaAiRoute
  '/portfolio': typeof PortfolioRoute
  '/quem-somos': typeof QuemSomosRoute
  '/radar-ai': typeof RadarAiRoute
  '/solucoes': typeof SolucoesRoute
  '/trilha-ai': typeof TrilhaAiRoute
  '/virada-inteligente': typeof ViradaInteligenteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-trabalhamos'
    | '/contato'
    | '/diagnostico'
    | '/forja-ai'
    | '/portfolio'
    | '/quem-somos'
    | '/radar-ai'
    | '/solucoes'
    | '/trilha-ai'
    | '/virada-inteligente'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/blog/'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-trabalhamos'
    | '/contato'
    | '/diagnostico'
    | '/forja-ai'
    | '/portfolio'
    | '/quem-somos'
    | '/radar-ai'
    | '/solucoes'
    | '/trilha-ai'
    | '/virada-inteligente'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/blog'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/como-trabalhamos'
    | '/contato'
    | '/diagnostico'
    | '/forja-ai'
    | '/portfolio'
    | '/quem-somos'
    | '/radar-ai'
    | '/solucoes'
    | '/trilha-ai'
    | '/virada-inteligente'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/blog/'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoTrabalhamosRoute: typeof ComoTrabalhamosRoute
  ContatoRoute: typeof ContatoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ForjaAiRoute: typeof ForjaAiRoute
  PortfolioRoute: typeof PortfolioRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RadarAiRoute: typeof RadarAiRoute
  SolucoesRoute: typeof SolucoesRoute
  TrilhaAiRoute: typeof TrilhaAiRoute
  ViradaInteligenteRoute: typeof ViradaInteligenteRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CasesSlugRoute: typeof CasesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabalhamos': {
      id: '/como-trabalhamos'
      path: '/como-trabalhamos'
      fullPath: '/como-trabalhamos'
      preLoaderRoute: typeof ComoTrabalhamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forja-ai': {
      id: '/forja-ai'
      path: '/forja-ai'
      fullPath: '/forja-ai'
      preLoaderRoute: typeof ForjaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar-ai': {
      id: '/radar-ai'
      path: '/radar-ai'
      fullPath: '/radar-ai'
      preLoaderRoute: typeof RadarAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha-ai': {
      id: '/trilha-ai'
      path: '/trilha-ai'
      fullPath: '/trilha-ai'
      preLoaderRoute: typeof TrilhaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virada-inteligente': {
      id: '/virada-inteligente'
      path: '/virada-inteligente'
      fullPath: '/virada-inteligente'
      preLoaderRoute: typeof ViradaInteligenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoTrabalhamosRoute: ComoTrabalhamosRoute,
  ContatoRoute: ContatoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ForjaAiRoute: ForjaAiRoute,
  PortfolioRoute: PortfolioRoute,
  QuemSomosRoute: QuemSomosRoute,
  RadarAiRoute: RadarAiRoute,
  SolucoesRoute: SolucoesRoute,
  TrilhaAiRoute: TrilhaAiRoute,
  ViradaInteligenteRoute: ViradaInteligenteRoute,
  BlogSlugRoute: BlogSlugRoute,
  CasesSlugRoute: CasesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
